apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./manifests/*
build:
  local:
    push: false
  artifacts:
    - image: prantab/accounts
      context: .
      docker:
        dockerfile: ./dockerfiles/accounts.dockerfile
      sync:
        manual:
          - src: "./services/accounts/**/*.js"
            dest: "."
    - image: prantab/inventory
      context: .
      docker:
        dockerfile: ./dockerfiles/inventory.dockerfile
      sync:
        manual:
          - src: "./services/inventory/**/*.js"
            dest: .
    - image: prantab/products
      context: .
      docker:
        dockerfile: ./dockerfiles/products.dockerfile
      sync:
        manual:
          - src: "./services/products/**/*.js"
            dest: .
    - image: prantab/reviews
      context: .
      docker:
        dockerfile: ./dockerfiles/reviews.dockerfile
      sync:
        manual:
          - src: "./services/reviews/**/*.js"
            dest: .
    - image: prantab/gateway
      context: ./
      docker:
        dockerfile: ./dockerfiles/gateway.dockerfile
      sync:
        manual:
          - src: "./**/*.js"
            dest: .
